### ISSUE TITLE
Malformed settings.ini

### ISSUE THREAD

**Issue by viruxe** [Southclaws/ScavengeSurvive#194]
First startup using Debian 8.3

```
server/motd =                                                                Please update the 'server/motd' string in SSS/settings.ini
server/website =                                                               southclawjk.wordpress.com
server/crash-on-exit =                                                              1
server/max-uptime =                                                             18000
player/allow-pause-map =                                                            0
player/interior-entry =                                                           0
player/player-animations =                                                          1
player/vehicle-surfing =                                                         0
player/nametag-distance =                                                        3.000000
player/combat-log-window =                                                       30
player/login-freeze-time =                                                      8
player/max-tab-out-time =                                                     60
player/ping-limit =                                                    400
server/global-debug-level =                                                   0
autosave/autosave-toggle =                                                  1
autosave/autosave-interval =                                                 60000
server/file-check =                                                0
infomessage/interval =                                               5
player-vehicle/print-each =                                              1
player-vehicle/print-total =                                             1
vehicle-spawn/spawn-chance =                                            4.000000
vehicle-spawn/print-each =                                           0
vehicle-spawn/print-total =                                          1
spawn/bagtype =                                         Satchel
server/whitelist =                                        0
server/whitelist-auto-toggle =                                       0
irc/use-irc =                                      0
irc/serv =                                     irc.tl
irc/port =                                    6667
irc/chat-chan =                                   #MyChatChannel
irc/chat-pass =                                  changeme
irc/chat-prefix =                                 46
irc/staff-chan =                                #MyStaffChannel
irc/staff-pass =                               changeme
irc/staff-prefix =                              46
irc/bot-name =                             SS-Bot
irc/bot-nick =                            SS-Bot
irc/bot-pass =                           changeme
irc/bot-mail =                          e@ma.il
irc/bot-user =                         SS-Bot
vehicle.damage/knock-mult =                        1.000000
vehicle.damage/bleed-mult =                       1.000000
defence/print-each-load =                      0
defence/print-total-load =                     1
defence/print-each-save =                    0
defence/print-total-save =                   1
defence/print-removes =                  0
safebox/print-each-load =                 0
safebox/print-total-load =                1
safebox/print-each-save =               0
safebox/print-total-save =              1
safebox/print-removes =             0
tent/print-each-load =            0
tent/print-total-load =           1
tent/print-each-save =          0
tent/print-total-save =         1
tent/print-removes =        0
sign/print-each-load =       0
sign/print-total-load =      1
sign/print-each-save =     0
sign/print-each-runtime-save =    0
sign/print-total-save =   1
sign/print-removes =  0
server/loot-spawn-multiplier = 1.000000

```

**Comment by viruxe** [comment]
In the mean time if someone else needs it, here is a properly formed settings file:

```
server/motd                  = Please update the 'server/motd' string in SSS/settings.ini
server/website               = southclawjk.wordpress.com
server/crash-on-exit         = 1
server/max-uptime            = 18000
player/allow-pause-map       = 0
player/interior-entry        = 0
player/player-animations     = 1
player/vehicle-surfing       = 0
player/nametag-distance      = 3.000000
player/combat-log-window     = 30
player/login-freeze-time     = 8
player/max-tab-out-time      = 60
player/ping-limit            = 400
server/global-debug-level    = 0
autosave/autosave-toggle     = 1
autosave/autosave-interval   = 60000
server/file-check            = 0
infomessage/interval         = 5
player-vehicle/print-each    = 1
player-vehicle/print-total   = 1
vehicle-spawn/spawn-chance   = 4.000000
vehicle-spawn/print-each     = 0
vehicle-spawn/print-total    = 1
spawn/bagtype                = Satchel
server/whitelist             = 0
server/whitelist-auto-toggle = 0
irc/use-irc                  = 0
irc/serv                     = irc.tl
irc/port                     = 6667
irc/chat-chan                = MyChatChannel
irc/chat-pass                = changeme
irc/chat-prefix              = 46
irc/staff-chan               = MyStaffChannel
irc/staff-pass               = changeme
irc/staff-prefix             = 46
irc/bot-name                 = SS-Bot
irc/bot-nick                 = SS-Bot
irc/bot-pass                 = changeme
irc/bot-mail                 = e@ma.il
irc/bot-user                 = SS-Bot
vehicle.damage/knock-mult    = 1.000000
vehicle.damage/bleed-mult    = 1.000000
defence/print-each-load      = 0
defence/print-total-load     = 1
defence/print-each-save      = 0
defence/print-total-save     = 1
defence/print-removes        = 0
safebox/print-each-load      = 0
safebox/print-total-load     = 1
safebox/print-each-save      = 0
safebox/print-total-save     = 1
safebox/print-removes        = 0
tent/print-each-load         = 0
tent/print-total-load        = 1
tent/print-each-save         = 0
tent/print-total-save        = 1
tent/print-removes           = 0
sign/print-each-load         = 0
sign/print-total-load        = 1
sign/print-each-save         = 0
sign/print-each-runtime-save = 0
sign/print-total-save        = 1
sign/print-removes           = 0
server/loot-spawn-multiplier = 1.000000
```

**Comment by Southclaw** [comment]
Was that the automatically written one? I'll look into that, my SimpleINI library handles all that so that's probably to blame. It should deal with whitespace before/after '=' fine though.

**Comment by viruxe** [comment]
Exactly. It starts with an amont of whitespaces and then it decreases to just one.

**Comment by DexX39** [comment]
Hello, I met the same concerns. Once the file is created and assigned values, the server will not start due to the bad indentation. So, it's a problem with SimpleINI when he read file ?

Best regards.

**Comment by Southclaw** [comment]
I can't actually reproduce this on Windows so it must be a Linux only thing, probably related to line endings somehow (I don't see how though). Unfortunately I don't have any Linux machines to test on right now.

**Comment by DexX39** [comment]
I'll see when I have more time to test it on Linux and see if the problems persist.

I have a tendency to say that it comes from "file_Save" or "file_Open".
Hope you can find the problem, meanwhile, DJSON does the job ^^

**Comment by viruxe** [comment]
I can provide a linux instance for testing if required.

**Comment by kadaradam** [comment]
Those spacings causes to fail to load the settings data. This issue only happens if you change the default value in the settings file. Basically what happens is after I generate the "settings.ini" file, and I change some value like the "server/whitelist" to 1 (true), and I log in the game the chat keeps spamming the MOTD text, and I can't log in, because the server freezes. If I [remove the spaces](http://www.miniwebtool.com/remove-spaces/), everything works fine.

Also there is been an issue on Windows. When you save the key and it's data, you won't break the line (only on Windows). It makes the text messy, but not a big deal.

**Comment by Southclaw** [comment]
I just pushed a commit I made 5 months ago and forgot to push, that might actually fix it too!

**Comment by kadaradam** [comment]
Yeah, that should do it. The problem was with the space after the '=' symbol.

**Comment by viruxe** [comment]
As of the latest release on this date this issue still remains. This time it's happening on Windows.
It is firstly generated like my first example without modifying anything. It works how it is for some settings but not for others. I had to remove all spaces before and after the equals sign.

Here is a working `settings.ini` file:
```
server/motd=Welcome to my server. Enjoy and invite your friends to a CHEAT-FREE server.
server/website=southcla.ws
server/crash-on-exit=0
server/rules/0=NO RULES!
server/staff/0=VIRUXE
server/max-uptime=32000
player/allow-pause-map=0
player/interior-entry=0
player/player-animations=1
player/vehicle-surfing=0
player/nametag-distance=3.000000
player/combat-log-window=30
player/login-freeze-time=8
player/max-tab-out-time=60
player/ping-limit=400
server/global-debug-level=0
infomessage/messages/0=The only exceptions for the Anti-Cheat that we know of is 'crashes.asi' and 'sensfix.asi'.
infomessage/messages/1=Using 'modloader.asi' gets you a 9 day global ban.
infomessage/messages/2=In the future we will try to add our own exceptions for the AC but for now just use a clean GTASA instance.
infomessage/messages/3=Please be aware that this server is temporarily hosted on my personal computer. Your ping will oscilate a lot.
infomessage/messages/4=Don't rememeber a crafting recipe? Visit ss.southcla.ws to access the Wiki.
infomessage/messages/5=Wan't to talk to me? You can find me at Southclaw's Discord server (http://dc.southcla.ws).
infomessage/messages/6=This server is usually open from only from 8:00 to 23:00 (UTC +00). If you wan't me to play longer just contact me.
infomessage/interval=5
player-vehicle/print-each=1
player-vehicle/print-total=1
vehicle-spawn/spawn-chance=4.000000
vehicle-spawn/print-each=0
vehicle-spawn/print-total=1
server/whitelist=0
server/whitelist-auto-toggle=0
irc/use-irc=0
irc/serv=irc.tl
irc/port=6667
irc/chat-chan=#MyChatChannel
irc/chat-pass=changeme
irc/chat-prefix=46
irc/staff-chan=#MyStaffChannel
irc/staff-pass=changeme
irc/staff-prefix=46
irc/bot-name=SS-Bot
irc/bot-nick=SS-Bot
irc/bot-pass=changeme
irc/bot-mail=e@ma.il
irc/bot-user=SS-Bot
vehicle.damage/knock-mult=1.000000
vehicle.damage/bleed-mult=1.000000
server/loot-spawn-multiplier=1.000000
autosave/autosave-toggle=1
autosave/autosave-interval=60000
spawn/bagtype=Satchel
spawn/new-blood=90.000000
spawn/new-food=80.000000
spawn/new-bleed=0.000099
spawn/new-items/0=Knife
spawn/res-blood=100.000000
spawn/res-food=40.000000
spawn/res-bleed=0.000000
spawn/res-items/0=AntiSepBandage
```

**Comment by Southclaws** [comment]
Maybe the issue moved from Linux to windows due to file endings?

I honestly have no idea why this issue would appear again, SimpleINI was fixed ages ago and it was tested on linux and windows. 🤔

**Comment by viruxe** [comment]
Perhaps it has something to do with system language?

**Comment by NegativeIQ** [comment]
@viruxe more likely encoding differences. Unix uses UTF-8 by default, while windows UTF-16 (LE or something like that).

**Comment by viruxe** [comment]
@NegativeIQ alright but I'm quite sure @Southclaws also has a local server on his computer where he tests the gamemode. And apparently he is not getting the same result as I am.

**Comment by NegativeIQ** [comment]
@viruxe well that could be explained with OS language (different languages use different encoding).
By the way what is your system locale language? (Its somewhere in Control panel -> region and language)

**Comment by viruxe** [comment]
It's PT-PT
